### PR TITLE
Added additional instruction to Readme

### PR DESCRIPTION
**Pull request by goonzoid**
It seems that Security.framework is required for this to build. I couldn't find that documented anywhere so I've added it to the Readme.

Thanks.

### CODE REVIEW

**Comment by aokj4ck** [comment]
Cool. Here’s my vote of confidence.

**Comment by ipranay** [comment]
That's right... another vote from me!

**Comment by ngreenstein** [comment]
Hi Will,

I can't reproduce this; `[BPXLUUIDHandler UUID]` works fine for me without `Security.framework`. What version of Xcode are you using and what version of iOS are you targeting?

Thanks

**Comment by eddydas** [comment]
vote up from me too
using xcode 4.6.3, target ios 6.0

got a bunch of these linker error when I didn't include Security.framework:

Undefined symbols for architecture armv7: "_kSecReturnAttributes", referenced from: ...

**Comment by goonzoid** [comment]
It's been over a year since I was using this on a project, so I can't remember exactly what version of Xcode etc. I was using at the time I'm afraid. I no longer have access to that codebase either.

**Comment by goonzoid** [comment]
I don't expect anything will ever happen with this, so I'm closing it.

**Pull request closed without merging**
